name: Build, Test and Deploy PreRelease

on:
  push:
    branches:
      - main

jobs:
  build-test-bump-version:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  

    - name: Build
      run: dotnet build --configuration Release --no-restore

   - name: Publish Demo
      run: dotnet publish .\DemoApp --configuration Release --output published-demo

    - name: Bump Version and Push Tag
      id: bump_version      
      uses:  mathieudutour/github-tag-action@v5.1
      with:
        release_branches: stable
        pre_release_branches : main
        github_token: ${{ secrets.GITHUB_TOKEN }}
        append_to_pre_release_tag: beta

    - name: Use the version
        run: |
          echo ${{ steps.bump_version.outputs.version }}
      - name: Use the previous version
        run: |
          echo ${{ steps.bump_version.outputs.previous-version }}
